from sqlalchemy import (
    Column,
    Date,
    DateTime,
    Integer,
    MetaData,
    Numeric,
    String,
    Table,
    Text,
)

CDM_SCHEMA = MetaData()

# Vocabulary Tables
concept = Table(
    "concept",
    CDM_SCHEMA,
    Column("concept_id", Integer, primary_key=True),
    Column("concept_name", String(255), nullable=False),
    Column("domain_id", String(20), nullable=False),
    Column("vocabulary_id", String(20), nullable=False),
    Column("concept_class_id", String(20), nullable=False),
    Column("standard_concept", String(1), nullable=True),
    Column("concept_code", String(50), nullable=False),
    Column("valid_start_date", Date, nullable=False),
    Column("valid_end_date", Date, nullable=False),
    Column("invalid_reason", String(1), nullable=True),
)

concept_ancestor = Table(
    "concept_ancestor",
    CDM_SCHEMA,
    Column("ancestor_concept_id", Integer, primary_key=True),
    Column("descendant_concept_id", Integer, primary_key=True),
    Column("min_levels_of_separation", Integer, nullable=False),
    Column("max_levels_of_separation", Integer, nullable=False),
)

# Clinical Tables
person = Table(
    "person",
    CDM_SCHEMA,
    Column("person_id", Integer, primary_key=True),
    Column("gender_concept_id", Integer, nullable=False),
    Column("year_of_birth", Integer, nullable=False),
    Column("month_of_birth", Integer, nullable=True),
    Column("day_of_birth", Integer, nullable=True),
    Column("birth_datetime", DateTime, nullable=True),
    Column("race_concept_id", Integer, nullable=False),
    Column("ethnicity_concept_id", Integer, nullable=False),
    Column("location_id", Integer, nullable=True),
    Column("provider_id", Integer, nullable=True),
    Column("care_site_id", Integer, nullable=True),
    Column("person_source_value", String(50), nullable=True),
    Column("gender_source_value", String(50), nullable=True),
    Column("gender_source_concept_id", Integer, nullable=True),
    Column("race_source_value", String(50), nullable=True),
    Column("race_source_concept_id", Integer, nullable=True),
    Column("ethnicity_source_value", String(50), nullable=True),
    Column("ethnicity_source_concept_id", Integer, nullable=True),
)

observation_period = Table(
    "observation_period",
    CDM_SCHEMA,
    Column("observation_period_id", Integer, primary_key=True),
    Column("person_id", Integer, nullable=False),
    Column("observation_period_start_date", Date, nullable=False),
    Column("observation_period_end_date", Date, nullable=False),
    Column("period_type_concept_id", Integer, nullable=False),
)

death = Table(
    "death",
    CDM_SCHEMA,
    Column("person_id", Integer, primary_key=True),
    Column("death_date", Date, nullable=False),
    Column("death_datetime", DateTime, nullable=True),
    Column("death_type_concept_id", Integer, nullable=False),
    Column("cause_concept_id", Integer, nullable=True),
    Column("cause_source_value", String(50), nullable=True),
    Column("cause_source_concept_id", Integer, nullable=True),
)

visit_occurrence = Table(
    "visit_occurrence",
    CDM_SCHEMA,
    Column("visit_occurrence_id", Integer, primary_key=True),
    Column("person_id", Integer, nullable=False),
    Column("visit_concept_id", Integer, nullable=False),
    Column("visit_start_date", Date, nullable=False),
    Column("visit_start_datetime", DateTime, nullable=True),
    Column("visit_end_date", Date, nullable=False),
    Column("visit_end_datetime", DateTime, nullable=True),
    Column("visit_type_concept_id", Integer, nullable=False),
    Column("provider_id", Integer, nullable=True),
    Column("care_site_id", Integer, nullable=True),
    Column("visit_source_value", String(50), nullable=True),
    Column("visit_source_concept_id", Integer, nullable=True),
    Column("admitted_from_concept_id", Integer, nullable=True),
    Column("admitted_from_source_value", String(50), nullable=True),
    Column("discharged_to_concept_id", Integer, nullable=True),
    Column("discharged_to_source_value", String(50), nullable=True),
    Column("preceding_visit_occurrence_id", Integer, nullable=True),
)

visit_detail = Table(
    "visit_detail",
    CDM_SCHEMA,
    Column("visit_detail_id", Integer, primary_key=True),
    Column("person_id", Integer, nullable=False),
    Column("visit_detail_concept_id", Integer, nullable=False),
    Column("visit_detail_start_date", Date, nullable=False),
    Column("visit_detail_start_datetime", DateTime, nullable=True),
    Column("visit_detail_end_date", Date, nullable=False),
    Column("visit_detail_end_datetime", DateTime, nullable=True),
    Column("visit_detail_type_concept_id", Integer, nullable=False),
    Column("provider_id", Integer, nullable=True),
    Column("care_site_id", Integer, nullable=True),
    Column("visit_detail_source_value", String(50), nullable=True),
    Column("visit_detail_source_concept_id", Integer, nullable=True),
    Column("admitted_from_concept_id", Integer, nullable=True),
    Column("admitted_from_source_value", String(50), nullable=True),
    Column("discharged_to_source_value", String(50), nullable=True),
    Column("discharged_to_concept_id", Integer, nullable=True),
    Column("preceding_visit_detail_id", Integer, nullable=True),
    Column("parent_visit_detail_id", Integer, nullable=True),
    Column("visit_occurrence_id", Integer, nullable=False),
)

condition_occurrence = Table(
    "condition_occurrence",
    CDM_SCHEMA,
    Column("condition_occurrence_id", Integer, primary_key=True),
    Column("person_id", Integer, nullable=False),
    Column("condition_concept_id", Integer, nullable=False),
    Column("condition_start_date", Date, nullable=False),
    Column("condition_start_datetime", DateTime, nullable=True),
    Column("condition_end_date", Date, nullable=True),
    Column("condition_end_datetime", DateTime, nullable=True),
    Column("condition_type_concept_id", Integer, nullable=False),
    Column("stop_reason", String(20), nullable=True),
    Column("provider_id", Integer, nullable=True),
    Column("visit_occurrence_id", Integer, nullable=True),
    Column("visit_detail_id", Integer, nullable=True),
    Column("condition_source_value", String(50), nullable=True),
    Column("condition_source_concept_id", Integer, nullable=True),
    Column("condition_status_source_value", String(50), nullable=True),
    Column("condition_status_concept_id", Integer, nullable=True),
)

drug_exposure = Table(
    "drug_exposure",
    CDM_SCHEMA,
    Column("drug_exposure_id", Integer, primary_key=True),
    Column("person_id", Integer, nullable=False),
    Column("drug_concept_id", Integer, nullable=False),
    Column("drug_exposure_start_date", Date, nullable=False),
    Column("drug_exposure_start_datetime", DateTime, nullable=True),
    Column("drug_exposure_end_date", Date, nullable=False),
    Column("drug_exposure_end_datetime", DateTime, nullable=True),
    Column("verbatim_end_date", Date, nullable=True),
    Column("drug_type_concept_id", Integer, nullable=False),
    Column("stop_reason", String(20), nullable=True),
    Column("refills", Integer, nullable=True),
    Column("quantity", Numeric, nullable=True),
    Column("days_supply", Integer, nullable=True),
    Column("sig", Text, nullable=True),
    Column("route_concept_id", Integer, nullable=True),
    Column("lot_number", String(50), nullable=True),
    Column("provider_id", Integer, nullable=True),
    Column("visit_occurrence_id", Integer, nullable=True),
    Column("visit_detail_id", Integer, nullable=True),
    Column("drug_source_value", String(50), nullable=True),
    Column("drug_source_concept_id", Integer, nullable=True),
    Column("route_source_value", String(50), nullable=True),
    Column("dose_unit_source_value", String(50), nullable=True),
)

procedure_occurrence = Table(
    "procedure_occurrence",
    CDM_SCHEMA,
    Column("procedure_occurrence_id", Integer, primary_key=True),
    Column("person_id", Integer, nullable=False),
    Column("procedure_concept_id", Integer, nullable=False),
    Column("procedure_date", Date, nullable=False),
    Column("procedure_datetime", DateTime, nullable=True),
    Column("procedure_end_date", Date, nullable=True),
    Column("procedure_end_datetime", DateTime, nullable=True),
    Column("procedure_type_concept_id", Integer, nullable=False),
    Column("modifier_concept_id", Integer, nullable=True),
    Column("quantity", Integer, nullable=True),
    Column("provider_id", Integer, nullable=True),
    Column("visit_occurrence_id", Integer, nullable=True),
    Column("visit_detail_id", Integer, nullable=True),
    Column("procedure_source_value", String(50), nullable=True),
    Column("procedure_source_concept_id", Integer, nullable=True),
    Column("modifier_source_value", String(50), nullable=True),
)

device_exposure = Table(
    "device_exposure",
    CDM_SCHEMA,
    Column("device_exposure_id", Integer, primary_key=True),
    Column("person_id", Integer, nullable=False),
    Column("device_concept_id", Integer, nullable=False),
    Column("device_exposure_start_date", Date, nullable=False),
    Column("device_exposure_start_datetime", DateTime, nullable=True),
    Column("device_exposure_end_date", Date, nullable=True),
    Column("device_exposure_end_datetime", DateTime, nullable=True),
    Column("device_type_concept_id", Integer, nullable=False),
    Column("unique_device_id", String(255), nullable=True),
    Column("production_id", String(255), nullable=True),
    Column("quantity", Integer, nullable=True),
    Column("provider_id", Integer, nullable=True),
    Column("visit_occurrence_id", Integer, nullable=True),
    Column("visit_detail_id", Integer, nullable=True),
    Column("device_source_value", String(50), nullable=True),
    Column("device_source_concept_id", Integer, nullable=True),
    Column("unit_concept_id", Integer, nullable=True),
    Column("unit_source_value", String(50), nullable=True),
    Column("unit_source_concept_id", Integer, nullable=True),
)

measurement = Table(
    "measurement",
    CDM_SCHEMA,
    Column("measurement_id", Integer, primary_key=True),
    Column("person_id", Integer, nullable=False),
    Column("measurement_concept_id", Integer, nullable=False),
    Column("measurement_date", Date, nullable=False),
    Column("measurement_datetime", DateTime, nullable=True),
    Column("measurement_time", String(10), nullable=True),
    Column("measurement_type_concept_id", Integer, nullable=False),
    Column("operator_concept_id", Integer, nullable=True),
    Column("value_as_number", Numeric, nullable=True),
    Column("value_as_concept_id", Integer, nullable=True),
    Column("unit_concept_id", Integer, nullable=True),
    Column("range_low", Numeric, nullable=True),
    Column("range_high", Numeric, nullable=True),
    Column("provider_id", Integer, nullable=True),
    Column("visit_occurrence_id", Integer, nullable=True),
    Column("visit_detail_id", Integer, nullable=True),
    Column("measurement_source_value", String(50), nullable=True),
    Column("measurement_source_concept_id", Integer, nullable=True),
    Column("unit_source_value", String(50), nullable=True),
    Column("unit_source_concept_id", Integer, nullable=True),
    Column("value_source_value", String(50), nullable=True),
    Column("measurement_event_id", Integer, nullable=True),
    Column("meas_event_field_concept_id", Integer, nullable=True),
)

observation = Table(
    "observation",
    CDM_SCHEMA,
    Column("observation_id", Integer, primary_key=True),
    Column("person_id", Integer, nullable=False),
    Column("observation_concept_id", Integer, nullable=False),
    Column("observation_date", Date, nullable=False),
    Column("observation_datetime", DateTime, nullable=True),
    Column("observation_type_concept_id", Integer, nullable=False),
    Column("value_as_number", Numeric, nullable=True),
    Column("value_as_string", String(60), nullable=True),
    Column("value_as_concept_id", Integer, nullable=True),
    Column("qualifier_concept_id", Integer, nullable=True),
    Column("unit_concept_id", Integer, nullable=True),
    Column("provider_id", Integer, nullable=True),
    Column("visit_occurrence_id", Integer, nullable=True),
    Column("visit_detail_id", Integer, nullable=True),
    Column("observation_source_value", String(50), nullable=True),
    Column("observation_source_concept_id", Integer, nullable=True),
    Column("unit_source_value", String(50), nullable=True),
    Column("qualifier_source_value", String(50), nullable=True),
    Column("value_source_value", String(50), nullable=True),
    Column("observation_event_id", Integer, nullable=True),
    Column("obs_event_field_concept_id", Integer, nullable=True),
)

specimen = Table(
    "specimen",
    CDM_SCHEMA,
    Column("specimen_id", Integer, primary_key=True),
    Column("person_id", Integer, nullable=False),
    Column("specimen_concept_id", Integer, nullable=False),
    Column("specimen_type_concept_id", Integer, nullable=False),
    Column("specimen_date", Date, nullable=False),
    Column("specimen_datetime", DateTime, nullable=True),
    Column("quantity", Numeric, nullable=True),
    Column("unit_concept_id", Integer, nullable=True),
    Column("anatomic_site_concept_id", Integer, nullable=True),
    Column("disease_status_concept_id", Integer, nullable=True),
    Column("specimen_source_id", String(50), nullable=True),
    Column("specimen_source_value", String(50), nullable=True),
    Column("unit_source_value", String(50), nullable=True),
    Column("anatomic_site_source_value", String(50), nullable=True),
    Column("disease_status_source_value", String(50), nullable=True),
)

# Health System
location = Table(
    "location",
    CDM_SCHEMA,
    Column("location_id", Integer, primary_key=True),
    Column("address_1", String(50), nullable=True),
    Column("address_2", String(50), nullable=True),
    Column("city", String(50), nullable=True),
    Column("state", String(2), nullable=True),
    Column("zip", String(9), nullable=True),
    Column("county", String(20), nullable=True),
    Column("location_source_value", String(50), nullable=True),
    Column("country_concept_id", Integer, nullable=True),
    Column("country_source_value", String(80), nullable=True),
    Column("latitude", Numeric, nullable=True),
    Column("longitude", Numeric, nullable=True),
)

care_site = Table(
    "care_site",
    CDM_SCHEMA,
    Column("care_site_id", Integer, primary_key=True),
    Column("care_site_name", String(255), nullable=True),
    Column("place_of_service_concept_id", Integer, nullable=True),
    Column("location_id", Integer, nullable=True),
    Column("care_site_source_value", String(50), nullable=True),
    Column("place_of_service_source_value", String(50), nullable=True),
)

provider = Table(
    "provider",
    CDM_SCHEMA,
    Column("provider_id", Integer, primary_key=True),
    Column("provider_name", String(255), nullable=True),
    Column("npi", String(20), nullable=True),
    Column("dea", String(20), nullable=True),
    Column("specialty_concept_id", Integer, nullable=True),
    Column("care_site_id", Integer, nullable=True),
    Column("year_of_birth", Integer, nullable=True),
    Column("gender_concept_id", Integer, nullable=True),
    Column("provider_source_value", String(50), nullable=True),
    Column("specialty_source_value", String(50), nullable=True),
    Column("specialty_source_concept_id", Integer, nullable=True),
    Column("gender_source_value", String(50), nullable=True),
    Column("gender_source_concept_id", Integer, nullable=True),
)

# Economics
payer_plan_period = Table(
    "payer_plan_period",
    CDM_SCHEMA,
    Column("payer_plan_period_id", Integer, primary_key=True),
    Column("person_id", Integer, nullable=False),
    Column("payer_plan_period_start_date", Date, nullable=False),
    Column("payer_plan_period_end_date", Date, nullable=False),
    Column("payer_source_value", String(50), nullable=True),
    Column("payer_source_concept_id", Integer, nullable=True),
    Column("plan_source_value", String(50), nullable=True),
    Column("plan_source_concept_id", Integer, nullable=True),
    Column("sponsor_source_value", String(50), nullable=True),
    Column("sponsor_source_concept_id", Integer, nullable=True),
    Column("family_source_value", String(50), nullable=True),
    Column("stop_reason_source_value", String(50), nullable=True),
    Column("stop_reason_source_concept_id", Integer, nullable=True),
)

cost = Table(
    "cost",
    CDM_SCHEMA,
    Column("cost_id", Integer, primary_key=True),
    Column("cost_event_id", Integer, nullable=False),
    Column("cost_domain_id", String(20), nullable=False),
    Column("cost_type_concept_id", Integer, nullable=False),
    Column("currency_concept_id", Integer, nullable=True),
    Column("total_charge", Numeric, nullable=True),
    Column("total_cost", Numeric, nullable=True),
    Column("total_paid", Numeric, nullable=True),
    Column("paid_by_payer", Numeric, nullable=True),
    Column("paid_by_patient", Numeric, nullable=True),
    Column("paid_patient_copay", Numeric, nullable=True),
    Column("paid_patient_coinsurance", Numeric, nullable=True),
    Column("paid_patient_deductible", Numeric, nullable=True),
    Column("paid_by_primary", Numeric, nullable=True),
    Column("paid_ingredient_cost", Numeric, nullable=True),
    Column("paid_dispensing_fee", Numeric, nullable=True),
    Column("payer_plan_period_id", Integer, nullable=True),
    Column("amount_allowed", Numeric, nullable=True),
    Column("revenue_code_concept_id", Integer, nullable=True),
    Column("revenue_code_source_value", String(50), nullable=True),
    Column("drg_concept_id", Integer, nullable=True),
    Column("drg_source_value", String(3), nullable=True),
)

# Derived
condition_era = Table(
    "condition_era",
    CDM_SCHEMA,
    Column("condition_era_id", Integer, primary_key=True),
    Column("person_id", Integer, nullable=False),
    Column("condition_concept_id", Integer, nullable=False),
    Column("condition_era_start_date", Date, nullable=False),
    Column("condition_era_end_date", Date, nullable=False),
    Column("condition_occurrence_count", Integer, nullable=True),
)

drug_era = Table(
    "drug_era",
    CDM_SCHEMA,
    Column("drug_era_id", Integer, primary_key=True),
    Column("person_id", Integer, nullable=False),
    Column("drug_concept_id", Integer, nullable=False),
    Column("drug_era_start_date", Date, nullable=False),
    Column("drug_era_end_date", Date, nullable=False),
    Column("drug_exposure_count", Integer, nullable=True),
    Column("gap_days", Integer, nullable=True),
)

dose_era = Table(
    "dose_era",
    CDM_SCHEMA,
    Column("dose_era_id", Integer, primary_key=True),
    Column("person_id", Integer, nullable=False),
    Column("drug_concept_id", Integer, nullable=False),
    Column("unit_concept_id", Integer, nullable=False),
    Column("dose_value", Numeric, nullable=False),
    Column("dose_era_start_date", Date, nullable=False),
    Column("dose_era_end_date", Date, nullable=False),
)
